name = "paper"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
gleam_community_colour = ">= 2.0.0 and < 3.0.0"
paint = ">= 2.0.0 and < 3.0.0"
prng = ">= 5.1.0 and < 6.0.0"
